name: CI Pipeline

# Trigger the workflow on push or pull request to main and development branches
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "Checkout successful!"

      # Build the project using Gradle
      - name: Build with Gradle
        run: .\gradlew.bat clean build
        shell: powershell
      - if: success()
        run: echo "Congratulation, build successful!"
      - if: failure()
        run: echo "Build failed!"

      # Run the tests
      - name: Run tests with Gradle
        run: .\gradlew.bat test
        shell: powershell
      - if: success()
        run: echo "Tests executed successfully!"
      - if: failure()
        run: echo "Tests execution failed!"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/responsive-web:latest .

      # Log in to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image to Docker Hub
      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/responsive-web:latest